// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyfesrkJ88LXJPi2VSwO_o0nR9aOhgrvA',
    appId: '1:662644286405:web:f95b7fdbc58c679a4e61ac',
    messagingSenderId: '662644286405',
    projectId: 'advertisement-ffe9a',
    authDomain: 'advertisement-ffe9a.firebaseapp.com',
    storageBucket: 'advertisement-ffe9a.appspot.com',
    measurementId: 'G-5H9VVSQJJM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwcau4GaZLpYnMOMjmffA_A0in4iGHPLs',
    appId: '1:662644286405:android:33e6630a28ad91fd4e61ac',
    messagingSenderId: '662644286405',
    projectId: 'advertisement-ffe9a',
    storageBucket: 'advertisement-ffe9a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV6neEz_IInZflp4MuLafgLOzmRUmtm3Y',
    appId: '1:662644286405:ios:7205e4c54abca3c74e61ac',
    messagingSenderId: '662644286405',
    projectId: 'advertisement-ffe9a',
    storageBucket: 'advertisement-ffe9a.appspot.com',
    iosClientId: '662644286405-t72vcvnufhd4fddc3f2rb74htsvvvc3c.apps.googleusercontent.com',
    iosBundleId: 'com.example.advertisement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV6neEz_IInZflp4MuLafgLOzmRUmtm3Y',
    appId: '1:662644286405:ios:46bb7aaf98697c304e61ac',
    messagingSenderId: '662644286405',
    projectId: 'advertisement-ffe9a',
    storageBucket: 'advertisement-ffe9a.appspot.com',
    iosClientId: '662644286405-de41egqpjhnme0qq04k87jms9ql9e9cu.apps.googleusercontent.com',
    iosBundleId: 'com.example.advertisement.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyfesrkJ88LXJPi2VSwO_o0nR9aOhgrvA',
    appId: '1:662644286405:web:987f2abcfe00d8d44e61ac',
    messagingSenderId: '662644286405',
    projectId: 'advertisement-ffe9a',
    authDomain: 'advertisement-ffe9a.firebaseapp.com',
    storageBucket: 'advertisement-ffe9a.appspot.com',
    measurementId: 'G-7V23TJS80Y',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyCyfesrkJ88LXJPi2VSwO_o0nR9aOhgrvA',
    appId: '1:662644286405:web:dc66065f422b0dce4e61ac',
    messagingSenderId: '662644286405',
    projectId: 'advertisement-ffe9a',
    authDomain: 'advertisement-ffe9a.firebaseapp.com',
    storageBucket: 'advertisement-ffe9a.appspot.com',
    measurementId: 'G-D04YF815DG',
  );
}
